### ISSUE TITLE
Timed permissions and group

### ISSUE THREAD

**Issue by tiradorus** [weaondara/BungeePerms#352] opened 2019-07-12 21:14 UTC
**Is your feature request related to a problem? Please describe.**
Not really, but a bit ^^' My server have monthly grade, and i have to manually remove the grade of players by the date of when they've bought the grade ... i'ts a long job sometimes.

And i wanna add a new feature that need timed permissions (global boost for a certain duration)

**Describe the solution you'd like**
Simply add a timer on a given permission or on an assigned group, just as PermissionEx do
For example:
`/bp user %player% add Permission.node 2h`

**Describe alternatives you've considered**
There are no alternatives of that ^^'

**Additional context**

Player use an item.
This item give him + 20% lootRate for 2 Hours
In reality, this item send to the console `/bp user %player_name% add Looting20`
Then, on a mob plugin, it check the permission of the player, and give him the loots by consequence of his perms.

+ it's a bungee Perm, so the lootrate is efficient on every server he came, and for the duration determined by the plugin. (Not a local duration for a local server)

**Comment by aurorasmiles** [comment] 2019-07-22 16:28
Duplicate of https://github.com/weaondara/BungeePerms/issues/8
We hope we can add that in V3.1, but there is no eta currently :/

**Closed by aurorasmiles** 2019-07-22 16:28 UTC
Labels: BP 3.1, duplicate, enhancement, future
