### ISSUE TITLE
the problem is not recoverable database

### ISSUE THREAD

**Issue by quaiby** [weaondara/BungeePerms#274] opened 2016-07-08 16:22 UTC
Sorry for my English, I hope you understand me.

I ONLY tuned db connection
useUUIDs: false
useregexperms: false
grouppermission: true
backendtype: MySQL2
uuidplayerdb: YAML
tablePrefix: bungeeperms_
uuidfetcher:
  cooldown: 3000
saveAllUsers: true
deleteUsersOnCleanup: false
notify:
  promote: false
  demote: false
tabcomplete: false
locale: en-GB
terminate:
  prefix:
    reset: true
    space: true
  suffix:
    reset: true
    space: true
cleanup:
  interval: 1800
  threshold: 600
async-commands: true
networktype: Global
networkservers: []
debug:
  path: xxx\bungee\plugins\BungeePerms/debug.log
  showexceptions: true
  showlogs: false
bungeeperms:
  general:
    mysqlhost: localhost
    mysqlport: '3306'
    mysqldb: bungeecord
    mysqluser: mysql
    mysqlpw: mysql

And plugin is breaks

19:18:37 [INFO] [BungeePerms] loading permissions ...
19:18:37 [SEVERE] java.lang.RuntimeException: java.sql.SQLException: Expression #1 of ORDER BY clause is not in SELECT list, references column 'bungeecord.bungeeperms_permissions2.id' which is not in SELECT list; this is incompatible with DISTINCT
19:18:37 [INFO] [BungeePerms] permissions loaded
19:18:37 [SEVERE]   at net.alpenblock.bungeeperms.Mysql.returnQuery(Mysql.java:232)
19:18:37 [SEVERE]   at net.alpenblock.bungeeperms.Mysql.returnQuery(Mysql.java:98)
19:18:37 [SEVERE]   at net.alpenblock.bungeeperms.io.mysql2.MysqlPermsAdapter2.getGroups(MysqlPermsAdapter2.java:44)
19:18:37 [SEVERE]   at net.alpenblock.bungeeperms.io.MySQL2BackEnd.loadGroups(MySQL2BackEnd.java:68)
19:18:37 [SEVERE]   at net.alpenblock.bungeeperms.PermissionsManager.loadPerms(PermissionsManager.java:116)
19:18:37 [SEVERE]   at net.alpenblock.bungeeperms.PermissionsManager.<init>(PermissionsManager.java:65)
19:18:37 [SEVERE]   at net.alpenblock.bungeeperms.BungeePerms.<init>(BungeePerms.java:56)
19:18:37 [SEVERE]   at net.alpenblock.bungeeperms.platform.bungee.BungeePlugin.onLoad(BungeePlugin.java:63)
19:18:37 [SEVERE]   at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:309)
19:18:37 [SEVERE]   at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
19:18:37 [SEVERE]   at net.md_5.bungee.BungeeCord.start(BungeeCord.java:258)
19:18:37 [SEVERE]   at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
19:18:37 [SEVERE]   at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
19:18:37 [SEVERE] Caused by: java.sql.SQLException: Expression #1 of ORDER BY clause is not in SELECT list, references column 'bungeecord.bungeeperms_permissions2.id' which is not in SELECT list; this is incompatible with DISTINCT
19:18:37 [SEVERE]   at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:996)
19:18:37 [SEVERE]   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
19:18:37 [SEVERE]   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
19:18:37 [SEVERE]   at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
19:18:37 [SEVERE]   at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
19:18:37 [SEVERE]   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2526)
19:18:37 [SEVERE]   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
19:18:37 [SEVERE]   at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1446)
19:18:37 [INFO] [BungeePerms] Activating BungeePerms ...
19:18:37 [SEVERE]   at net.alpenblock.bungeeperms.Mysql.returnQuery(Mysql.java:218)
19:18:37 [SEVERE]   ... 12 more

I use BungeeCord 1.9.4 and BungeePerms 3.0.0 dev #47

**Comment by CodeCrafter47** [comment] 2016-07-08 19:49
Duplicate of #252 . The information there might help you to fix the issue.

**Closed** 2019-02-12 21:13 UTC
