### ISSUE TITLE
MySQL issue

### ISSUE THREAD

**Issue by Rokirok** [weaondara/BungeePerms#281] opened 2016-08-20 19:29 UTC
**Error:**

21:23:51 [INFO] [BungeePerms] extracting lang/EN-gb.yml
21:23:51 [INFO] [BungeePerms] extracted lang/EN-gb.yml
21:23:53 [INFO] [BungeePerms] loading permissions ...
21:23:53 [SEVERE] java.lang.RuntimeException: java.sql.SQLException: Expression #1 of ORDER BY clause is not in SELECT list, references column 'bungeeperms.bungeeperms_permissions2.id' which is not in SELECT list; this is incompatible with DISTINCT
21:23:53 [SEVERE]   at net.alpenblock.bungeeperms.Mysql.returnQuery(Mysql.java:232)
21:23:53 [SEVERE]   at net.alpenblock.bungeeperms.Mysql.returnQuery(Mysql.java:98)
21:23:53 [SEVERE]   at net.alpenblock.bungeeperms.io.mysql2.MysqlPermsAdapter2.getGroups(MysqlPermsAdapter2.java:44)
21:23:53 [INFO] [BungeePerms] permissions loaded
21:23:53 [SEVERE]   at net.alpenblock.bungeeperms.io.MySQL2BackEnd.loadGroups(MySQL2BackEnd.java:68)
21:23:53 [SEVERE]   at net.alpenblock.bungeeperms.PermissionsManager.loadPerms(PermissionsManager.java:116)
21:23:53 [SEVERE]   at net.alpenblock.bungeeperms.PermissionsManager.<init>(PermissionsManager.java:65)
21:23:53 [SEVERE]   at net.alpenblock.bungeeperms.BungeePerms.<init>(BungeePerms.java:56)
21:23:53 [SEVERE]   at net.alpenblock.bungeeperms.platform.bungee.BungeePlugin.onLoad(BungeePlugin.java:63)
21:23:53 [SEVERE]   at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:309)
21:23:53 [SEVERE]   at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
21:23:53 [SEVERE]   at net.md_5.bungee.BungeeCord.start(BungeeCord.java:264)
21:23:53 [SEVERE]   at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:111)
21:23:53 [SEVERE]   at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
21:23:53 [SEVERE] Caused by: java.sql.SQLException: Expression #1 of ORDER BY clause is not in SELECT list, references column 'bungeeperms.bungeeperms_permissions2.id' which is not in SELECT list; this is incompatible with DISTINCT
21:23:53 [SEVERE]   at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:996)
21:23:53 [SEVERE]   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
21:23:53 [SEVERE]   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
21:23:53 [SEVERE]   at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
21:23:53 [SEVERE]   at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
21:23:53 [SEVERE]   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2526)
21:23:53 [SEVERE]   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
21:23:53 [SEVERE]   at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1446)
21:23:53 [SEVERE]   at net.alpenblock.bungeeperms.Mysql.returnQuery(Mysql.java:218)
21:23:53 [SEVERE]   ... 12 more
21:23:53 [INFO] Loaded plugin BungeePerms version 3.0 dev #47 by wea_ondara

**Using:
Server version: 5.7.13-0ubuntu0.16.04.2 (Ubuntu)**

**Comment by CodeCrafter47** [comment] 2016-08-21 08:35
Duplicate of #252

**Closed** 2016-12-24 11:35 UTC
